

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Write value from Properties-file
      id: write_property
      uses: Reedyuk/write-properties@v1.0.1
      with:
        path: './Configuration/config.properties'
        property: 'URL'
        value: 'www.google.com'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

