

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        name: env_url
        url: https://www.google.com

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    - name: Write value from Properties-file
      id: write_property
      uses: Reedyuk/write-properties@v1.0.1
      with:
        path: './Configuration/config.properties'
        property: URL
        value: ${{ inputs.env_url }}

    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.1.0
      with:
        path: './Configuration/config.properties'
        properties: BROWSER URL

    - name: Build with Maven
      run: mvn -B package --file pom.xml

